# Generated by Django 5.1.3 on 2024-11-30 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('naziv', models.CharField(db_column='NAZIV', max_length=30)),
                ('sprat', models.IntegerField(blank=True, db_column='SPRAT', null=True)),
                ('strana_sveta', models.CharField(blank=True, db_column='STRANA_SVETA', max_length=30, null=True)),
                ('username', models.CharField(blank=True, db_column='USERNAME', max_length=30, null=True)),
                ('password', models.CharField(blank=True, db_column='PASSWORD', max_length=30, null=True)),
                ('tip', models.CharField(blank=True, db_column='TIP', max_length=30, null=True)),
            ],
            options={
                'db_table': 'FIRMA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kartice',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('encrypted_card', models.BinaryField(blank=True, db_column='ENCRYPTED_CARD', null=True)),
            ],
            options={
                'db_table': 'KARTICE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('ime', models.CharField(db_column='IME', max_length=30)),
                ('prezime', models.CharField(db_column='PREZIME', max_length=30)),
                ('email', models.CharField(blank=True, db_column='EMAIL', max_length=30, null=True)),
                ('broj_telefona', models.CharField(blank=True, db_column='BROJ_TELEFONA', max_length=30, null=True)),
                ('username', models.CharField(blank=True, db_column='USERNAME', max_length=30, null=True)),
                ('password', models.CharField(blank=True, db_column='PASSWORD', max_length=30, null=True)),
            ],
            options={
                'db_table': 'KORISNIK',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Popust',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('encrypted_card', models.BinaryField(blank=True, db_column='ENCRYPTED_CARD', max_length=30, null=True)),
                ('iskoriscen', models.BooleanField(blank=True, db_column='ISKORISCEN', max_length=30, null=True)),
            ],
            options={
                'db_table': 'POPUST',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Promocija',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('iskorisceno', models.IntegerField(blank=True, db_column='ISKORISCENO', null=True)),
                ('ukupno', models.IntegerField(blank=True, db_column='UKUPNO', null=True)),
                ('minimalan_iznos', models.IntegerField(blank=True, db_column='MINIMALAN_IZNOS', null=True)),
                ('od', models.DateTimeField(blank=True, db_column='OD', null=True)),
                ('do', models.DateTimeField(blank=True, db_column='DO', null=True)),
                ('flat_popust', models.IntegerField(blank=True, db_column='FLAT_POPUST', null=True)),
                ('procenat_popust', models.IntegerField(blank=True, db_column='PROCENAT_POPUST', null=True)),
                ('max_iznos', models.IntegerField(blank=True, db_column='MAX_IZNOS', null=True)),
            ],
            options={
                'db_table': 'PROMOCIJA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pos',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'POS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transakcije',
            fields=[
                ('id_t', models.AutoField(db_column='ID_T', primary_key=True, serialize=False)),
                ('encrypted_card', models.BinaryField(blank=True, db_column='ENCRYPTED_CARD', null=True)),
                ('iznos', models.IntegerField(blank=True, db_column='IZNOS', null=True)),
                ('datum_vreme', models.DateTimeField(blank=True, db_column='DATUM_VREME', null=True)),
                ('popust', models.BooleanField(blank=True, db_column='POPUST', null=True)),
            ],
            options={
                'db_table': 'TRANSAKCIJE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PopustFirma',
            fields=[
                ('idp', models.OneToOneField(db_column='IDP', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='MelonApp.promocija')),
            ],
            options={
                'db_table': 'POPUST_FIRMA',
                'managed': False,
            },
        ),
    ]
