# Generated by Django 5.1.3 on 2024-12-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MelonApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('encrypted_card', models.BinaryField(blank=True, db_column='ENCRYPTED_CARD', null=True)),
                ('iznos', models.IntegerField(blank=True, db_column='IZNOS', null=True)),
            ],
            options={
                'db_table': 'PARKING',
                'managed': False,
            },
        ),
    ]
